name: Update Site
on: [push, workflow_dispatch]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Output
        run: |
          rm .gitignore
          python3 -m pip install -r requirements.txt
          python3 generate.py
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
